apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: baw-project
    type: keycloak
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: baw-project
    type: keycloak
