apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: ingress

spec:
  ingressClassName: nginx
  rules:
  # - host: project.baw
  -  http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
