apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql
  labels:
    app: baw-project
    type: keycloak-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: baw-project
    type: keycloak-postgresql
