apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql-data
  labels:
    app: baw-project
    type: keycloak-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard
